let students = [ 
    {name:'Pallavi Thanguturu',user:'pallaviii1210'},
{name:'Spoortika',user:'Spoortika'},
{name:'Sai Krishna',user:'Saikrishna15035'},
{name:'O. Santhosh',user:'Santhu19s'},
{name:'Snehith Reddy B',user:'snehithreddybanala03'},
{name:'Tanuja Prathipati',user:'tanuja-prathipati'},
{name:'V C Sreehaasa',user:'vc-s'},
{name:'Nayandeep',user:'nayan9924'},
{name:'Bytakpatil Balaji',user:'BytakpatilBalaji123'},
{name:'V.Srihitha',user:'Srihitha47'},
{name:'Goutham Krishna',user:'goutham1611'},
{name:'Praveen Raj',user:'praveenrajofficial0'},
{name:'Kwisha Shah',user:'kwishashah'},
{name:'Sowmya',user:'SowmyaManukonda'},
{name:'Srihitha Medi',user:'srihithamedi'},
{name:'Bolla Aniksha',user:'aniksha24'},
{name:'kalyan',user:'Kalyan036'},
{name:'Shaik Kareena',user:'kareena6009'},
{name:'Sruthika',user:'sruthika111'},
{name:'Koyyada Saipooja',user:'Saipooja02'},
{name:'P.Vaishnavi',user:'Vaishnavi5265'},
{name:'B.Niharika',user:'Niharika237'},
{name:'Sydugari Srinaya',user:'Srinaya29'},
{name:'Abhinav U',user:'abhinavu0701'},
{name:'Sathwika',user:'Sathwika2411'},
{name:'Rishitha',user:'rishithabhatt'},
// {name:'Prasanna Katipally',user:'PrasannaKatipally'},
{name:'GunjalaSiddartha',user:'GunjalaSiddartha'},
{name:'Koushik Reddy',user:'koushikreddyperi'},
{name:'Kethavath Pavankalyan',user:'k-pavankalyan'},
{name:'Gayathri Kodipaka',user:'GayathriKodipaka'},
{name:'Patlolla Vardhana',user:'Varuu04'},
{name:'Kompalli Sri Divya',user:'DivyaKompalli'},
{name:'T Varshini',user:'Varshini8916'},
{name:'K.Geetha',user:'GeethaKethavath'},
{name:'G.Saipriya',user:'Saipriya-173'},
{name:'G S PANKAJ',user:'Cosmovate'},
{name:'Himadri Chakraborty',user:'Himadri-16'},
{name:'N.vishal',user:'github-visual'},
{name:'P. Sai Sneha',user:'Sneha0317'},
{name:'Srihitha Simhadri',user:'SRIHITHA0'},
{name:'Rishikesh potha',user:'Rishikeshpotha'},
{name:'Sandeep Mouli',user:'Sandeep7003'},
{name:'Harshitha',user:'harshitha-1911'},
{name:'Aravind Bathula',user:'Aravind-3110'},
{name:'Chidvilasini',user:'Chidvilasin29'},
{name:'Shashi Kiran',user:'kiran739642'},
{name:'Akash.P',user:'akash10233'},
{name:'jatin',user:'Jatin2805'},
{name:'Prasanna Katipally',user:'prasannakatipally'},
{name:'Aneesh Bashaboina',user:'Aneeshitsc'},
{name:'Sai Bhaskar',user:'saibhaskar15702'},
{name:'Harshitha Chakicherla',user:'harshithachakicherla'},
{name:'Chitte Maneesh',user:'maneeshchitte'},
{name:'Garlapalli Hridaya',user:'Hridaya08'},
{name:'Ajay Panyala',user:'ajaypanyala02'},
{name:'Aneesh Bashaboina',user:'Aneeshitsc'},
{name:'Srinidhi Kothakapu',user:'SrinidhiKothakapu'},
{name:'Hari krishna',user:'hari-0604'},
{name:'J.Ramya',user:'jalagamramyaa'},
{name:'sairisheek',user:'sairisheek4'},
{name:'Jatin',user:'Jatin2805'},
{name:'Svapnnika',user:'Svapnnika'},
{name:'Svapnnika',user:'Svapnnika'},
{name:'Hiranya',user:'madupuhiranya'},
{name:'Gorrepati Akshaya',user:'Akshaya_289868'},
{name:'Kota Avinash',user:'Kotaavinash14112004'},
{name:'MOKSHITH REDDY M',user:'Nani080'},
{name:'Srivalli',user:'srivallig18'},
{name:'Chethan Kumar Ganji',user:'chethan3065'},
{name:'Guruvannagari Rishi',user:'rishirao07'},
{name:'SUPRAJA',user:'supraja425'},
{name:'Sanjana Ganji',user:'Sanjana5523'},
{name:'Riyan',user:'RIYAN3412'},
{name:'Sindhu',user:'sindhu1301'},
{name:'Hasini Kadali',user:'Hasinikadali'},
{name:'Abhiram Bonagiri',user:'AbhiramBonagiri'},
{name:'Snehith Ambewar',user:'snehith1308'},
{name:'Anusha',user:'Anusha2456'},
{name:'K.SAHIT',user:'KSAHIT'},
{name:'Abhishek',user:'abhishek25n'},
{name:'A santhosh',user:'Santhosh17062005'},
{name:'Yashasvi',user:'Yashasvi692'},
{name:'Kalyani Advala',user:'kalyaniadvala'},
{name:'srivarsha',user:'Srivarshalinga'},
{name:'Nithinkumar',user:'Nithinkumar2710'},
{name:'Poojith Rangineni',user:'PoojithRangineni'},
{name:'Vishnu Vardhan',user:'vishnuec'},
{name:'Pranay Gaddameedi',user:'pranay8940'},
{name:'K.Sanjay',user:'SanjayKuna'},
{name:'N.Sankeerthana',user:'sankeerthana0302'},
{name:'Mahender',user:'Mahender0223'},
{name:'Yadavalli Vinesh',user:'YadavalliVinesh'},
{name:'Y.mohana kalyani',user:'mohana65'},
{name:'V.Gangothri',user:'gangothri15'},
{name:'Praneeth Ravuri',user:'rpraneeths'},
{name:'Poojith Rangineni',user:'PoojithRangineni'},
{name:'Akshitha Kotte',user:'akshithakotte'},
{name:'krishnaveni pastam',user:'krishnaveni45'},
{name:'Shekar',user:'shekar345'},
{name:'krishnaveni pastam',user:'krishnaveni45'},
{name:'Victor Joseph',user:'victorjoseph02'},
{name:'Bhupathi Sreemeghana',user:'Sreemeghana17'},
{name:'Karthik Chowdary',user:'karthikck8143'},
{name:'Quadeer',user:'Quadeer-Q'},
{name:'Akhil Kasturi',user:'akhil00045'},
{name:'Sudheendra V',user:'Sudheendrav'},
{name:'Jayasri',user:'Jayasri934'},
{name:'R. Sree Tripura',user:'sreetripura'},
{name:'Sai Kiran',user:'saikiranobali45'},
    ];