let students = [
    { name: "Jishnu sai", user: "Jishnu1501" ,rank:3},
    { name: "Tarun Sandilya", user: "professionaltarun2004" ,rank:3},
    { name: "Anusha.T", user: "anusha0225" ,rank:3},
    { name: "vijay chakali", user: "vijaychanduri" ,rank:3},
    { name: "Varsha", user: "Varsha-9" ,rank:3},
    { name: "P Sai Ruthvika", user: "ruthvikap" ,rank:3},
    { name: "Arra Deepthi", user: "arradeepthi" ,rank:3},
    { name: "Shruthi", user: "Shruthi27015" ,rank:3},
    { name: "Aravind Medi", user: "Aravind-medi-14" ,rank:3},
    { name: "Astuti Sinha", user: "itsastutiii" ,rank:3},
    { name: "Kaushal Kulkarni", user: "kaushal-345" ,rank:3},
    { name: "Sriya", user: "sriya7824" ,rank:3},
    { name: "G.Ananya", user: "ananya08ganapuram" ,rank:3},
    { name: "Vinod Makkala", user: "vinod-makkala77" ,rank:3},
    { name: "P.PRANAVSAI", user: "Pranavsai1410" ,rank:3},
    { name: "Rajavardhan Reddy", user: "rajavardhan-03" ,rank:3},
    { name: "Bhavya Parupalli", user: "Bhavya-Parupalli" ,rank:3},
    { name: "Harsha Vardhini", user: "Harshavardhini84" ,rank:3},
    { name: "Mokshith naidu", user: "Mokshithnaidu14" ,rank:3},
    { name: "Aruna Sekhar", user: "arunasekhary" ,rank:3},
    { name: "P.Pavan Kalyan", user: "pavan123kalyan" ,rank:3},
    { name: "Anushka Kumar", user: "ak-2609" ,rank:3},
    { name: "Sravani", user: "ammu29-09" ,rank:3},
    { name: "Nithya", user: "LunarExplorer21" ,rank:3},
    { name: "G.Malleshwari", user: "Malleshwari614" ,rank:3},
    { name: "Harminder Kour", user: "hk1105" ,rank:3},
    { name: "Mohana Pusuluru", user: "mohana1805" ,rank:3},
    { name: "Kethana", user: "kethanachowdary" ,rank:3},
    { name: "Yochana P", user: "Yochhhhh" ,rank:3},
    { name: "kavya Boddu", user: "kavya-310" ,rank:3},
    { name: "Chandrabhanuprasad", user: "bhanu07x" ,rank:3},
    { name: "Purna Rupika", user: "PurnaRupika" ,rank:3},
    { name: "Kurremla Nikitha", user: "NikithaKurremla" ,rank:3},
    { name: "sumaiya khushnum", user: "sumaiya-58" ,rank:3},
    { name: "Lalit Aditya", user: "Lalit-58" ,rank:3},
    { name: "Anusha.T", user: "anusha0225" ,rank:3},
    { name: "P. Pragna Reddy", user: "PragnaReddy20" ,rank:3},
    { name: "A.Harshith", user: "harshithreddy12377" ,rank:3},
    { name: "Manaswi Thotla", user: "Manaswithotla17" ,rank:3},
    { name: "B.Akshitha", user: "Akshitha246" ,rank:3},
    { name: "Dheeraj Thummalapenta", user: "dt7768181" ,rank:3},
    { name: "Shyamala Akhila", user: "akhilashyamala90" ,rank:3},
    { name: "Sai Varshith", user: "ssvc2005" ,rank:3},
    { name: "saiteja", user: "saitejaambati" ,rank:3},
    { name: "Thumma Sai Krishna", user: "thummasaikrishna" ,rank:3},
    { name: "I.Ruthwik Sai", user: "iruthwiksai" ,rank:3},
    { name: "N.Sravya", user: "nadirgesravya" ,rank:3},
    { name: "Pavan Kumar", user: "Pavan024506" ,rank:3},
    { name: "Medisetti Vinutna", user: "vinutna1204" ,rank:3},
    { name: "Kammam Meghana", user: "KammamMeghana" ,rank:3},
    { name: "Kamati Sravani", user: "sravanikamati09" ,rank:3},
    { name: "Siddoju Nagavarshith", user: "VarshithSidhoju" ,rank:3},
    { name: "Karthik Gandla", user: "gkarthik2710" ,rank:3},
    { name: "Rohan Venkat", user: "rohanvenkat229" ,rank:3},
    { name: "khajamohinuddin", user: "khaja1818" ,rank:3},
    { name: "A Veera Prasad", user: "Veeraarigela" ,rank:3},
    { name: "Gaddi Sai Krishna", user: "gaddisai" ,rank:3},
    { name: "kappi ganesh", user: "Ganeshk2005" ,rank:3},
    { name: "Varshith", user: "varshith-0405" ,rank:3},
    { name: "Addanki Sai Sujith", user: "SujithAddanki" ,rank:3},
    { name: "Shivani", user: "Shivani19406" ,rank:3},
    { name: "Sai Srujana", user: "srujana345" ,rank:3},
    { name: "Mani Sivani Valluri", user: "sivani111" ,rank:3},
    { name: "Shinde Harshitha", user: "Harshitha374" ,rank:3},
    { name: "Mamatha Remudala", user: "Mamatha7d" ,rank:3},
    { name: "Manne Ankitha", user: "ankithamanne" ,rank:3},
    { name: "Tirtha gonepelly", user: "Tirtha047" ,rank:3},
    { name: "Nithika Reddy", user: "Nithika05" ,rank:3},
    { name: "Manvitha Reddy", user: "manvithareddychintha" ,rank:3},
    { name: "Uthkarsh", user: "uthkarsh1628" ,rank:3},
    { name: "AJAY NAG", user: "Ajaynag2326" ,rank:3},
    { name: "Bandarupalli Pranitha", user: "B-Pranitha" ,rank:3},
    { name: "amrutha", user: "amrutha0208" ,rank:3},
    { name: "deepesh reddy", user: "deepesh729" ,rank:3},
    { name: "N.Sushmitha", user: "sushmithanagula" ,rank:3},
    { name: "N.vyshnavi", user: "vyshnavi5544" ,rank:3},
    { name: "sannitha", user: "sannitha-kalewar" ,rank:3},
    { name: "Vinukonda Ushaswini", user: "ushaswinivinukonda" ,rank:3},
    { name: "G.Mukhesh", user: "mukhesh22" ,rank:3},
    { name: "Satvikeya", user: "Satvikeya" ,rank:3},
    { name: "Lohitha gouri", user: "lohithagouri" ,rank:3},
    { name: "Rahul Sangubotla", user: "RahulSangubotla" ,rank:3},
    { name: "Ayush Singh", user: "IDKYICODE" ,rank:3},
    { name: "Vagmi reddy", user: "Vagmireddy" ,rank:3},
    { name: "Abdul Samad", user: "reporanger07" ,rank:3},
    { name: "Ajay", user: "ajayinjapuri" ,rank:3},
    { name: "RASHMI JANNU", user: "rashmijannu" ,rank:3},
    {name:'Vellamchety Naga Sai Hari Priya',user:'NagaSaiHariPriya05',rank:3},
    {name:'A. Prabhas Chandra',user:'Pchandra2005',rank:3},
    {name:'Lok Vardhan',user:'lok005',rank:3},
    {name:'Dinesh Ragipani',user:'Dineshragipani',rank:3},
    {name:'vvpsaiganesh',user:'ganesh-61',rank:3},
    {name:'sowmya',user:'sowmya567',rank:3},
    {name:'Siddhartha',user:'siddharth0518',rank:3},
    {name:'Dhruvan Kanthali',user:'kanthalidhruvan',rank:3},
    {name:'charanya',user:'charanyachiluka',rank:3},
    {name:'T.Mallikarjuna chary',user:'mallikchary',rank:3},
    {name:'M.Manideep',user:'Manideep9308',rank:3},
    {name:'T.Sree Kumar Reddy',user:'tsreekumarreddy',rank:3},
    {name:'R Girish Reddy',user:'girishreddy14',rank:3},
    {name:'Praneeth seri',user:'Praneeth8888',rank:3},
    {name:'Gouni Parinitha Reddy',user:'ParinithaReddy05',rank:3},
    {name:'Heena Begum',user:'Heena-Begum516',rank:3},
    {name:'yedla saivenkat reddy',user:'saivenkat577',rank:3},
    {name:'Geyasri',user:'Geyasri2004',rank:3},
    {name:'Nishal M',user:'nishalm123',rank:3},
    {name:'Sathwika',user:'Sathwika171201',rank:3},
    {name:'Bharath Kumar',user:'Bharathkumar918',rank:3},
    {name:'Manoj',user:'ManojJallipalli',rank:3},
    {name:'Sai Krishna Enugu',user:'saikrishnardy',rank:3},
    {name:'Neeraj',user:'neeraj2442',rank:3},
    {name:'Velivela Purva Akshita',user:'Purvaakshita',rank:3},
    {name:'Vankudavath Anusha',user:'anushapamar18',rank:3},
    {name:'SAI KIRAN',user:'Saikiran0609',rank:3},
    {name:'Y.Smitha',user:'smithagithu',rank:3},
    {name:'Vanam Sai Krishna',user:'Saikrishna261004',rank:3},
    {name:'Keerthana Gunjala',user:'keerthana045',rank:3},
    {name:'C. Manogna',user:'Manogna24-tech',rank:3},
    {name:'Charishma Reddy',user:'Charishma-1234',rank:3},
    {name:'S.Poojitha',user:'Pooja1231234',rank:3},
    {name:'yedla saivenkat reddy',user:'saivenkat577',rank:3},
    {name:'Manish kumar',user:'Manish-925',rank:3},
    {name:'Sakshi Besi',user:'sakshi19',rank:3},
    {name:'saivarshit',user:'saivarshit080',rank:3},
    {name:'VISLAVATH GOVIND',user:'VGovind',rank:3},
    {name:'POLE SAMPATH KUMAR',user:'sampathkumarpole16',rank:3},
    {name:'Sasank',user:'Sasank8654',rank:3},
    {name:'Raithu srija',user:'Raithusrija',rank:3},
    {name:'Priyadarshini',user:'Honeypriya21',rank:3},
    {name:'Afreen Mohammad',user:'Afreen234',rank:3},
    {name:'Sasank',user:'Sasank8654',rank:3},
    {name:'P Shoumik',user:'shoumik0908',rank:3},
    {name:'Sakshi Besi',user:'sakshi-1919',rank:3},
    {name:'Praneeth',user:'praneeth1812',rank:3},
    {name:'Gadepranay',user:'gadepranay32',rank:3},
    {name:'Srujan',user:'srujan1607',rank:3},
    {name:'Omkar',user:'Omkar1293',rank:3},
    {name:'Renish',user:'RenishReddy',rank:3},
    {name:'David Kumar',user:'iamtony19',rank:3},
    {name:'Vaishnavi',user:'Vaishnavi1027',rank:3},
    {name:'Shreshta',user:'kandagatlashreshta',rank:3},
    {name:'Pranalee',user:'prana2024',rank:3},
    {name:'Harshithasai',user:'harshithasai123',rank:3},
    {name:'Lavanya',user:'itikalalavanya',rank:3},
    {name:'Samrudhi',user:'samrudhipuranik16',rank:3},
    {name:'Praveen Kumar',user:'praveenKumar-112',rank:3},
    {name:'Prasanna',user:'prasanna-1405',rank:3},
    {name:'Pavantej',user:'PavanS219',rank:3},
    {name:'Shaik Afroz',user:'shaiksafroz12345',rank:3},
    {name:'Akanksha',user:'akansha-215',rank:3},
    {name:'Nissi',user:'nissig',rank:3},
    {name:'Mahesh',user:'mah1212ar',rank:3},
    {name:'Pradeep',user:'trpradeep27',rank:3},
    {name:'Rahul',user:'RahulStanley',rank:3},
    {name:'Nishanth',user:'nishisspamm',rank:3},
    {name:'Thanishka',user:'thanishka28',rank:3},
    {name:'Anurag',user:'AnuragMothuku',rank:3},
    {name:'Sai Kiran',user:'Reddy-7',rank:3},
    {name:'Thakur',user:'thakur-hriday',rank:3},
    {name:'Nagesh',user:'NageshBabu-123',rank:3},
    {name:'Shreshta',user:'shreshtashesh',rank:3},
    {name:'Sai Asrith',user:'saiasrith75',rank:3},
    {name:'Charan',user:'saicharan-2',rank:3},
    {name:'Kethan',user:'Kethan1308',rank:3},
    {name:'Ratan',user:'ratan1824',rank:3},
    {name:'Nithish',user:'vasamnithish',rank:3},
    {name:'Athul Krishna',user:'athulkrishna09',rank:3},
    {name:'Rahul',user:'rahulpashikanti2468',rank:3},
    {name:'Sinduja',user:'M-Sinduja',rank:3},
    {name:'S Vikram',user:'vikrams1111',rank:3},
    {name:'T Saikumar',user:'sk22241a0560',rank:3},
    {name:'B Sravan',user:'sravansunny1111',rank:3},

  ];