let students = [ 
    {name:'Pallavi Thanguturu',user:'pallavii1210'},
{name:'Spoortika',user:'Spoortika'},
{name:'SAI KRISHNA JAKKOJU',user:'Saikrishna15035'},
{name:'O. Santhosh',user:'Santhu19s'},
{name:'Snehith Reddy B',user:'snehithreddybanala03'},
{name:'Tanuja Prathipati',user:'tanuja-prathipati'},
{name:'V C Sreehaasa',user:'vc-s'},
{name:'Nayandeep',user:'nayan9924'},
{name:'Bytakpatil Balaji',user:'BytakpatilBalaji123'},
{name:'V.Srihitha',user:'Srihitha47'},
{name:'GOUTHAM KRISHNA RAM',user:'goutham1611'},
{name:'Praveen Raj',user:'praveenrajofficial0'},
{name:'Kwisha Shah',user:'kwishashah'},
{name:'Sowmya',user:'SowmyaManukonda'},
{name:'Srihitha Medi',user:'srihithamedi'},
{name:'Bolla Aniksha',user:'aniksha24'},
{name:'kalyan',user:'Kalyan036'},
{name:'Shaik Kareena',user:'kareena6009'},
{name:'Sruthika',user:'sruthika111'},
{name:'Koyyada Saipooja',user:'Saipooja02'},
{name:'P.Vaishnavi',user:'Vaishnavi5265'},
{name:'B.Niharika',user:'Niharika237'},
{name:'Sydugari Srinaya',user:'Srinaya29'},
{name:'Abhinav U',user:'abhinavu0701'},
{name:'Sathwika',user:'Sathwika2411'},
{name:'Rishitha',user:'rishithabhatt'},
// {name:'Prasanna Katipally',user:'PrasannaKatipally'},
{name:'GunjalaSiddartha',user:'GunjalaSiddartha'},
{name:'Koushik Reddy',user:'koushikreddyperi'},
{name:'Kethavath Pavankalyan',user:'k-pavankalyan'},
{name:'Gayathri Kodipaka',user:'GayathriKodipaka'},
{name:'Patlolla Vardhana',user:'Varuu04'},
{name:'Kompalli Sri Divya Muktha',user:'DivyaKompalli'},
{name:'T Varshini',user:'Varshini8916'},
{name:'K.Geetha',user:'GeethaKethavath'},
{name:'G.Saipriya',user:'Saipriya-173'},
{name:'G S PANKAJ',user:'Cosmovate'},
{name:'Himadri Chakraborty',user:'Himadri-16'},
{name:'N.vishal',user:'github-visual'},
{name:'P. Sai Sneha',user:'Sneha0317'},
{name:'Srihitha Simhadri',user:'SRIHITHA0'},
{name:'Rishikesh potha',user:'Rishikeshpotha'},
{name:'Sandeep Mouli',user:'Sandeep7003'},
{name:'Harshitha',user:'HarshithaPoluka'},
{name:'Aravind Bathula',user:'Aravind-3110'},
{name:'Chidvilasini',user:'Chidvilasin29'},
{name:'Shashi Kiran',user:'kiran739642'},
{name:'Akash.P',user:'akash10233'},
{name:'jatin',user:'Jatin2805'},
{name:'Prasanna Katipally',user:'prasannakatipally'},
{name:'Aneesh Bashaboina',user:'Aneeshitsc'},
{name:'Sai Bhaskar',user:'saibhaskar15702'},
{name:'Harshitha Chakicherla',user:'harshithachakicherla'},
{name:'Chitte Maneesh',user:'maneeshchitte'},
{name:'Garlapalli Hridaya',user:'Hridaya08'},
{name:'Ajay Panyala',user:'ajaypanyala02'},
{name:'Aneesh Bashaboina',user:'Aneeshitsc'},
{name:'Srinidhi Kothakapu',user:'SrinidhiKothakapu'},
{name:'Hari krishna',user:'hari-0604'},
{name:'J.Ramya',user:'jalagamramyaa'},
{name:'sairisheek',user:'sairisheek4'},
{name:'Jatin',user:'Jatin2805'},
{name:'Svapnnika',user:'Svapnnika'},
{name:'Svapnnika',user:'Svapnnika'},
{name:'Hiranya',user:'madupuhiranya'},
{name:'Gorrepati Akshaya',user:'Akshaya_289868'},


    ];